title: Cason
description: "Class of 2025"
owner_name: Cason Pollak
github_username: casonpollak
github_repo: "cason_2025"
baseurl: "/cason_2025"
future: true
# remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - platform: github
      user_url: "https://github.com/nighthawkcoders"
    - platform: x
      user_url: "https://x.com/NighthawkCoding/"
    - platform: youtube
      user_url: "https://www.youtube.com/@nighthawkcodingsociety2868"
remote_theme: pages-themes/midnight
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/ideas.md
  - navigation/rpg.md
  - navigation/search.md
  - navigation/about.md
  - README4YML.md
  - navigation/interests.md